import socket
sock = socket.socket()
sock.connect (("127.0.0.0", 1234))
print ("Соединение установлено!")
sock.send("Привет!".encode("utf-8"))
print("Сообщение \n Привет! \n отправлено!")
data = sock.recv(1024)
sock.close()
print (data)
print("Соединение закрыто")